### PR TITLE
Get rid of old DNS resolver + improvements

### LINKED ISSUE #71: DnsResolver uses hardcoded DNS server
Hi,

I am using Xamarin Forms and recently updated with latest Nuget package, it works fine in simulator but on connection it is crashing when I run on physical device.

Thanks

### PR DESCRIPTION
**Pull request by ForNeVeR**
I have verified that `new LookupClient()`, indeed, crashes on Android emulator, and it works after this patch.

Also, there's now a possibility to configure the name server used.

And, finally, there's an improved connection cancellation for the web socket API.

Closes #71.

### CODE REVIEW

**Comment by vitalyster** [comment]
This is a case when we need conditionals: we should use the default nameserver when possible and use a hardcoded one only when the platform resolver is known to be broken.

**Comment by ForNeVeR** [comment]
What kind of condition would serve this purpose, though? I'm not aware of any Xamarin-related targets which are available in the stable SDK.

**Comment by vitalyster** [comment]
I don't know too, but there is no reason to change one hardcoded resolver to another, so this should be merged only when we find conditionals for mobile platforms

**Comment by ForNeVeR** [comment]
I don't think this is possible, or will be possible even in .NET 6.

The best that I was able to find is [a list of Xamarin-related TFMs](https://docs.microsoft.com/en-us/dotnet/standard/frameworks), which have the following downsides:
- only .NET 5 and .NET 6
- so, the user app should target .NET 5 or 6 to use a library packed in this way
- also, there isn't a single runtime for everything, but separate TFMs for `net6.0-android`, `net6.0-ios`, `net6-tvos` etc. This would require us to closely follow this list and update our package when new mobile platforms arise (which isn't that much of a problem, I guess), and also would require us to make N copies of our code for various platforms (i.e. `net6.0-android` + `net6.0-ios` which are the same for our code, but require distinct DLL copies)

**Comment by vitalyster** [comment]
Alternative solution - try to locate the bug in System.Dns (or where this crash happen exactly) and report upstream

**Comment by vitalyster** [comment]
And the third solution - check if it is NOT crashed if all required permissions to query system resolver are granted in the mobile app

**Comment by ForNeVeR** [comment]
Superseded by #128.

**Pull request closed without merging**
