### PR TITLE
Moved BookmarkManager to XmppConnection

### PR DESCRIPTION
**Pull request by kimimaru4000**
This PR moves the BookmarkManager to `XmppConnection` to allow easily connecting to MUC rooms over WebSockets. 

Important to note that the BookmarkManager is not instantiated in the base `XmppConnection` class but only in `XmppClient` and `XmppWebSocketConnection`. Please review and let me know if you find improvements. Thank you!

### CODE REVIEW

**Comment by kimimaru4000** [comment]
Hi @ForNeVeR, can you review this when you have time? Thank you!

**Review by ForNeVeR — APPROVED** [review]
I apologize for the pause, folks.

The changes are LGTM.

Do you think it's useful to release an update with this onto nuget.org right now?

**Comment by kimimaru4000** [comment]
Thanks for the review! I think others will find value in having these changes available on NuGet.

**Comment by ForNeVeR** [comment]
Fair enough. I'll start the release train, then.

**Pull request merged**
